# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('title', models.CharField(max_length=75, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='slider', verbose_name='Imagem')),
                ('sequence', models.IntegerField(default=0, verbose_name='Ordem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Banner Principal',
                'verbose_name_plural': 'Banners Principais',
            },
        ),
    ]
