# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170223_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_reservations',
            field=models.CharField(blank=True, help_text='+99 99 99999-9999 ou (99) 99999-9999', max_length=17, verbose_name='Telefone para Reservas'),
        ),
    ]
