# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170223_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('title', models.CharField(max_length=75, verbose_name='Título')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Sobre a Casa',
                'verbose_name_plural': 'Sobre as Casas',
            },
        ),
        migrations.CreateModel(
            name='AboutHouseDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('title', models.CharField(blank=True, max_length=75, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('about_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions_about_house', to='core.AboutHouse', verbose_name='Descrição (Sobre a Casa)')),
            ],
            options={
                'verbose_name': 'Descrição (Sobre a Casa)',
                'verbose_name_plural': 'Descrições (Sobre a Casa)',
            },
        ),
        migrations.CreateModel(
            name='AboutHouseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('title', models.CharField(blank=True, max_length=75, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('about_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_about_house', to='core.AboutHouse', verbose_name='Imagem (Sobre a Casa)')),
            ],
            options={
                'verbose_name': 'Imagem (Sobre a Casa)',
                'verbose_name_plural': 'Imagens (Sobre a Casa)',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('name', models.CharField(max_length=75, verbose_name='Nome')),
                ('email', models.EmailField(max_length=75, verbose_name='Email')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
