# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170415_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('sequence', models.IntegerField(default=0, verbose_name='Ordem')),
                ('title', models.CharField(max_length=256, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Nosso Sabor',
                'verbose_name_plural': 'Nossos Sabores',
                'ordering': ['sequence', '-created'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('sequence', models.IntegerField(default=0, verbose_name='Ordem')),
                ('title', models.CharField(max_length=256, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagem')),
                ('thumb', models.ImageField(upload_to='', verbose_name='Thumbnail')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.Menu', verbose_name='Prato')),
            ],
            options={
                'verbose_name': 'Prato',
                'verbose_name_plural': 'Pratos',
                'ordering': ['sequence', '-created'],
            },
        ),
    ]
