# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_menu_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('sequence', models.IntegerField(default=0, verbose_name='Ordem')),
                ('number', models.IntegerField(verbose_name='Número da Mesa')),
                ('quantity', models.IntegerField(verbose_name='Quantidade de Cadeiras')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem da Mesa')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['sequence', 'number', '-created'],
            },
        ),
    ]
