# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_restauranttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('phone', models.CharField(help_text='(99) 99999-9999', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('quantity', models.IntegerField(verbose_name='Quantidade de Cadeiras')),
                ('time_stamped', models.DateTimeField(verbose_name='Data e Hora')),
                ('active', models.BooleanField(default=False, help_text='Confirmação de reserva', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-time_stamped', '-created'],
            },
        ),
    ]
