# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_restaurantreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='reservations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.RestaurantReservation', verbose_name='Mesas'),
        ),
    ]
