# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170527_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttable',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Número da Mesa'),
        ),
    ]
