# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 13:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170527_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantreservation',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Quantidade de Cadeiras'),
        ),
    ]
