#!/bin/bash

NAME="quintal_varjota_app"                                  # Name of the application
PROJECTROOT=/webapps/quintal_varjota_django                 # The root path of project
DJANGODIR=/webapps/quintal_varjota_django/quintal_varjota   # Django project directory
SOCKFILE=/webapps/quintal_varjota_django/run/gunicorn.sock  # we will communicte using this unix socket
USER=quintal_varjota                                        # the user to run as
GROUP=webapps                                               # the group to run as
NUM_WORKERS=3                                               # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=quintal_varjota.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=quintal_varjota.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $PROJECTROOT
source ./bin/activate

cd $DJANGODIR
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
cd $PROJECTROOT && exec bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-
